name: widgets_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Agregamos el directorio que contiene nuestros recursos estáticos.
  # Y OJO hay que tener mucho pero mucho cuidado con la tabulación,
  # ya que si no esta correctamente tabulado nos va a dar error porque
  # no encuentra los assets.
  assets:
    - assets/images/